---

- name: ensure is-it-phishy folder exists
  file: path={{ phish_dir }} state=directory

- name: Get is-it-phishy from git
  git: repo=git@github.com:Fogetti/fogetti-phish-storm-ui.git dest={{ phish_dir }} force=yes version=master

- name: Install the latest changes
  npm: path={{ phish_dir }}

- name: restart is-it-phishy
  command: "{{ phish_restart_cmd }}"
  environment:
    REDIS_HOST: "{{ redis_host }}"
    REDIS_PORT: "{{ redis_port }}"
    REDIS_AUTH: "{{ redis_auth }}"
    KAFKA_HOST: "{{ kafka_host }}"
    KAFKA_PORT: "{{ kafka_port }}"
    KAFKA_REQUEST_TOPIC: "{{ kafka_request_topic }}"
    KAFKA_RESPONSE_TOPIC: "{{ kafka_response_topic }}"
    KAFKA_ZK_CONNECTION: "{{ kafka_zk_connection }}"
    HTTP_LISTEN_ADDRESS: "{{ http_listen_address }}"
    HTTP_PORT: "{{ http_port }}"
    HTTPS_PORT: "{{ https_port }}"